### ISSUE TITLE
Fortnite emotes

### ISSUE THREAD

**Issue by Blenux** [Befzz/blender3d_import_psk_psa#11] opened 2018-04-27 15:39 UTC
Hey man how things, just wondering if they is any updates coming to this addon, currently animation emotes from Fortnite ain't looking in properly, 

https://i.imgur.com/HdQPzJc.png

has you can see from the picture, where I am cycled it is completely messed up, the actorXimport from gildor works like a charm, however I'm more used to Blender on etc and be nice if you can have a update for this perhaps?

Thanks for your time.

**Comment by ArchUser87** [comment] 2018-05-16 17:43
Found the issue, these 4 bones are the cause of it, 

root = Root
spine_01 = Spine_01
spine_02 = Spine_02
spine_03 =Spine_03

Once I did that, the animations load in fine, is there anyway to have the bone names have caps on them automatically?

**Comment by Befzz** [comment] 2018-06-08 20:44
pushed to ["latest" branch](https://github.com/Befzz/blender3d_import_psk_psa/tree/latest).

    
ActorXImporter, was [patched](https://github.com/gildor2/UModel/blob/master/Tools/MaxActorXImport/ActorXImporter.ms) for that 😃 :
>  Revision History:
	19.05.2018 v1.36
	- using case-insensitive comparison when finding bones in scene for animation

**Comment by ArchUser87** [comment] 2018-06-09 01:09
Awesome job man thanks

**Comment by ArchUser87** [comment] 2018-06-09 04:27
There is a slight issue though, the animations are working great, however there is a problem with some bones that make the mesh all screwed up, like so.

Blender 2.7
![pskerror2 7](https://user-images.githubusercontent.com/25260650/41187627-df492e58-6bf0-11e8-8d43-f26da0df7f9c.PNG)

also in Blender 2.8
![pskerror2 8](https://user-images.githubusercontent.com/25260650/41187629-e577fd18-6bf0-11e8-9eb0-427ab106accb.PNG)

Also with Blender 2.8, can't select more then one skeleton armature when importing a animation file, though understandable if this is due to early development etc...

Hope these are fixable, do not that these seem to only be with Fortnite assets, PUBG work great, so understandable also if your not incline to fix.

Thanks, Blenux.

**Comment by ArchUser87** [comment] 2018-06-09 05:43
Track down the issue (so wish I knew how to fix in the code also lol), turns out the vertex groups on the mesh get screwed up because of the caps now, so that case-sensitive update fixes for the skeleton but when it caps vertex groups, causes issues, but unknown why it's only the head and not the body etc.

**Comment by ArchUser87** [comment] 2018-06-09 05:46
2.79
![vertex_caps_issue_279](https://user-images.githubusercontent.com/25260650/41188111-3ba39e44-6bfc-11e8-9272-fb753f3ebc31.PNG)

2.80
![vertex_caps_issue_280](https://user-images.githubusercontent.com/25260650/41188113-3e480496-6bfc-11e8-8af2-e917b9b50d00.PNG)

**Comment by Befzz** [comment] 2018-06-09 10:21
can you share some problematic **psk/psa** files?

**Comment by ArchUser87** [comment] 2018-06-09 12:03
Can upload soon.

**Comment by ArchUser87** [comment] 2018-06-09 12:35
https://mega.nz/#F!ZRMyyBLa!_ZChdp4np6GRQ5GbWfa3Yg

**Comment by Befzz** [comment] 2018-06-09 15:16
Wrong animation is not related to vertex groups.  

Vertex group names formed from a bone name. By renaming it, you just making it inactive(bone have no influence anymore).

Issue with animation importing was in this plugin and it still exists.  

I don't know how to rewrite that part of code in a correct way 😄 

Armature selection:
In 270: selected(3D View) will be used
In 280: choosed in 3D View _Panel_. If none, then selected in a 3D view

Before it was:
Choosed in 3D View Panel. If none, then selected _first imported_

**Comment by ArchUser87** [comment] 2018-06-09 16:10
oh ok, might just batch it all through 3ds max to fbx lol, slowly waiting for gLTF support to get better, so Gildor can implement it into uModel someday, just waiting on skeleton support I believe.

**Comment by Befzz** [comment] 2018-06-15 18:29
WiP for 2.7x 😄 😄 😄 

![pskpsaimport_tease](https://user-images.githubusercontent.com/1160036/41483684-bd23aa78-70e2-11e8-8d7e-2d928e1e441c.jpg)

**Comment by ArchUser87** [comment] 2018-06-16 03:32
Oh wow what was the cause?

**Comment by Befzz** [comment] 2018-06-16 03:45
Calculation of pose(bone) location/rotation now done in python instead of forcing a blender to do it.
(from armature space to "pose bone local" space)

You can test ( version 2.7x ): 
commit: https://github.com/Befzz/blender3d_import_psk_psa/commit/ca2bec0602294cd735c3baeb3c625867f7ab1670

*latest branch*: https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Comment by ArchUser87** [comment] 2018-06-16 04:18
ah nice, awesome fix man keep up the good work, will this be transferred to 2.80, has I still can't select more then 1 armature, after loaded in either the head or body, sorry to be a pain lol...

**Comment by ArchUser87** [comment] 2018-06-16 08:18
Right I manage to get the animations in Blender 2.80 by not using the Armature Selected of your importer for 2.80, and just have the armature selected, just has you did in the latest branch..

**Comment by Befzz** [comment] 2018-06-22 04:10
animation import now works with oriented bones.
2,8 now supported (at least that build that i have)

io_import_scene_unreal_psa_psk_270.py at 
https://github.com/Befzz/blender3d_import_psk_psa/tree/latest/addons

**Closed** 2018-10-24 21:01 UTC
